services:
  http-server:
    build:
      context: ./http_server
      dockerfile: ./Dockerfile
    ports: 
      - '8080:80'
      
  splitter:
    build:
      context: ./splitter
      dockerfile: ./Dockerfile
    ports: 
      - '3035:3035'


    